# Generated by Django 4.2.6 on 2025-01-03 18:24

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='service.servicemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='service', chained_model_field='service', on_delete=django.db.models.deletion.CASCADE, to='service.categorymodel'),
        ),
    ]
