# Generated by Django 4.2.6 on 2025-01-03 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_productmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
