# Generated by Django 4.2.6 on 2025-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_productmodel_created_at_productmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='description',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(default=1, verbose_name='Category Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='description_about',
            field=models.TextField(default=1, verbose_name='Description About Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='description_product',
            field=models.TextField(default=1, verbose_name='Description Product Service'),
            preserve_default=False,
        ),
    ]
