# Generated by Django 4.2.6 on 2025-01-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_portfoliomodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images/', verbose_name='Category Image'),
        ),
    ]
