# Generated by Django 4.2.6 on 2025-01-25 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_categorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Products Description'),
        ),
    ]
