# Generated by Django 4.2.6 on 2025-01-29 13:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_portfoliomodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Category Description'),
        ),
    ]
