# Generated by Django 4.2.6 on 2025-01-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_clientmodel_fullname_remove_clientmodel_jobs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientModel',
        ),
    ]
