# Generated by Django 4.2.6 on 2025-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_contactmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Images'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
