# Generated by Django 4.2.6 on 2025-01-06 17:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_articlemodel_images_delete_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(max_length=250, verbose_name='News Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content News')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='message',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content Article'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title Article'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
    ]
