# Generated by Django 4.2.6 on 2025-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_newsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='Images'),
        ),
    ]
