# Generated by Django 4.2.6 on 2025-01-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_aboutmodel_image_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='job_title',
        ),
    ]
